export const snapshot = {
  "status": {
    "last_update": "2026-09-26T23:34:32.811644+00:00",
    "cut_date": "2026-09-26",
    "movement_count": 474,
    "current_month": "2026-09-01",
    "plan_month": "2026-10-01",
    "planning_enabled": true,
    "exact_duplicates": 2,
    "possible_duplicates": 43,
    "missing_fx": 0,
    "pending_classification": 0,
    "current_budget_realistic": 632.08,
    "forecast_current": 706.99,
    "forecast_realistic": 657.06,
    "forecast_aggressive": 575.58
  },
  "dashboard": {
    "income_sustainable": 429.75,
    "salary_collected": 429.75,
    "personal_spend": 544.19,
    "monthly_budget": 632.08,
    "monthly_available": 87.89,
    "monthly_consumed_pct": 0.861,
    "biweekly_spend": 126.66,
    "biweekly_budget": 316.04,
    "biweekly_available": 189.38,
    "safe_to_spend": 189.38,
    "saving_target": -202.33,
    "saving_rate": -0.4708,
    "biweekly_period": 2,
    "salary_collected_biweekly": 0.0
  },
  "categories": [
    {
      "category": "Alimentación",
      "subcategory": "Comer fuera",
      "spent": 13.0,
      "budget": 16.01,
      "available": 3.01,
      "consumed_pct": 0.812,
      "status": "NEAR_LIMIT"
    },
    {
      "category": "Alimentación",
      "subcategory": "Comida a domicilio",
      "spent": 26.78,
      "budget": 7.86,
      "available": -18.92,
      "consumed_pct": 3.4071,
      "status": "EXCEEDED"
    },
    {
      "category": "Alimentación",
      "subcategory": "Mercado / Hogar",
      "spent": 133.38,
      "budget": 230.0,
      "available": 96.62,
      "consumed_pct": 0.5799,
      "status": "WITHIN"
    },
    {
      "category": "Alimentación",
      "subcategory": "Snacks / Antojos",
      "spent": 23.16,
      "budget": 31.14,
      "available": 7.98,
      "consumed_pct": 0.7437,
      "status": "WITHIN"
    },
    {
      "category": "Casa",
      "subcategory": "Productos de Limpieza",
      "spent": 9.43,
      "budget": 0.0,
      "available": -9.43,
      "consumed_pct": 0.0,
      "status": "NO_BUDGET"
    },
    {
      "category": "Comisiones",
      "subcategory": "Bancarias",
      "spent": 4.02,
      "budget": 3.13,
      "available": -0.89,
      "consumed_pct": 1.2843,
      "status": "EXCEEDED"
    },
    {
      "category": "Comisiones",
      "subcategory": "Pago móvil",
      "spent": 1.0,
      "budget": 0.87,
      "available": -0.13,
      "consumed_pct": 1.1494,
      "status": "EXCEEDED"
    },
    {
      "category": "Cuidado personal",
      "subcategory": "Barbería / Estética",
      "spent": 0.0,
      "budget": 11.0,
      "available": 11.0,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Deuda / CASHEA",
      "subcategory": "Cuota existente",
      "spent": 110.97,
      "budget": 131.65,
      "available": 20.68,
      "consumed_pct": 0.8429,
      "status": "NEAR_LIMIT"
    },
    {
      "category": "Deuda / CASHEA",
      "subcategory": "Nueva compra / Inicial",
      "spent": 3.3,
      "budget": 4.91,
      "available": 1.61,
      "consumed_pct": 0.6721,
      "status": "WITHIN"
    },
    {
      "category": "Gastos Anilet",
      "subcategory": "Alimentación",
      "spent": 3.93,
      "budget": 12.08,
      "available": 8.15,
      "consumed_pct": 0.3253,
      "status": "WITHIN"
    },
    {
      "category": "Gastos Anilet",
      "subcategory": "Cuidado personal",
      "spent": 0.0,
      "budget": 0.0,
      "available": 0.0,
      "consumed_pct": 0.0,
      "status": "NO_ACTIVITY"
    },
    {
      "category": "Gastos Anilet",
      "subcategory": "Otros",
      "spent": 0.0,
      "budget": 0.26,
      "available": 0.26,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Gastos Anilet",
      "subcategory": "Salud",
      "spent": 0.0,
      "budget": 0.4,
      "available": 0.4,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Gastos Anilet",
      "subcategory": "Telecomunicaciones",
      "spent": 2.41,
      "budget": 1.26,
      "available": -1.15,
      "consumed_pct": 1.9127,
      "status": "EXCEEDED"
    },
    {
      "category": "Mascotas",
      "subcategory": "Veterinario",
      "spent": 19.6,
      "budget": 0.0,
      "available": -19.6,
      "consumed_pct": 0.0,
      "status": "NO_BUDGET"
    },
    {
      "category": "Moto",
      "subcategory": "Reparación",
      "spent": 50.0,
      "budget": 0.0,
      "available": -50.0,
      "consumed_pct": 0.0,
      "status": "NO_BUDGET"
    },
    {
      "category": "Movilidad",
      "subcategory": "Envío / Mandado personal",
      "spent": 0.0,
      "budget": 0.0,
      "available": 0.0,
      "consumed_pct": 0.0,
      "status": "NO_ACTIVITY"
    },
    {
      "category": "Movilidad",
      "subcategory": "Transporte público",
      "spent": 2.14,
      "budget": 1.34,
      "available": -0.8,
      "consumed_pct": 1.597,
      "status": "EXCEEDED"
    },
    {
      "category": "Movilidad",
      "subcategory": "Traslado personal",
      "spent": 43.23,
      "budget": 37.37,
      "available": -5.86,
      "consumed_pct": 1.1568,
      "status": "EXCEEDED"
    },
    {
      "category": "Ocio",
      "subcategory": "Entretenimiento",
      "spent": 0.0,
      "budget": 2.02,
      "available": 2.02,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Ocio",
      "subcategory": "Hotel / Alojamiento",
      "spent": 13.84,
      "budget": 27.98,
      "available": 14.14,
      "consumed_pct": 0.4946,
      "status": "WITHIN"
    },
    {
      "category": "Salud",
      "subcategory": "Medicinas",
      "spent": 0.0,
      "budget": 25.0,
      "available": 25.0,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Salud",
      "subcategory": "Otros Salud",
      "spent": 27.2,
      "budget": 0.0,
      "available": -27.2,
      "consumed_pct": 0.0,
      "status": "NO_BUDGET"
    },
    {
      "category": "Suscripciones / Herramientas",
      "subcategory": "CapCut",
      "spent": 0.0,
      "budget": 10.01,
      "available": 10.01,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Suscripciones / Herramientas",
      "subcategory": "ChatGPT",
      "spent": 0.0,
      "budget": 20.0,
      "available": 20.0,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Suscripciones / Herramientas",
      "subcategory": "RIAL",
      "spent": 0.0,
      "budget": 5.79,
      "available": 5.79,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Tecnología",
      "subcategory": "Equipos",
      "spent": 0.0,
      "budget": 5.0,
      "available": 5.0,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Telecomunicaciones",
      "subcategory": "Internet",
      "spent": 37.21,
      "budget": 32.0,
      "available": -5.21,
      "consumed_pct": 1.1628,
      "status": "EXCEEDED"
    },
    {
      "category": "Trabajo / Trámites",
      "subcategory": "Documentos / Gestiones",
      "spent": 0.0,
      "budget": 15.0,
      "available": 15.0,
      "consumed_pct": 0.0,
      "status": "WITHIN"
    },
    {
      "category": "Trabajo / Trámites",
      "subcategory": "Mensajería / Traslado de documentos",
      "spent": 0.0,
      "budget": 0.0,
      "available": 0.0,
      "consumed_pct": 0.0,
      "status": "NO_ACTIVITY"
    },
    {
      "category": "Vestimenta",
      "subcategory": "Ropa",
      "spent": 19.59,
      "budget": 0.0,
      "available": -19.59,
      "consumed_pct": 0.0,
      "status": "NO_BUDGET"
    }
  ],
  "planner": {
    "CURRENT": {
      "current_budget": 675.0,
      "forecast": 706.99,
      "suggested": 706.99,
      "final": 706.99,
      "expected_saving": -277.24,
      "expected_saving_pct": -0.6451,
      "confidence_high": 5,
      "confidence_medium": 18,
      "confidence_low": 9,
      "planning_enabled": true,
      "state": "DRAFT",
      "plan_month": "2026-10-01",
      "scenario": "CURRENT"
    },
    "REALISTIC": {
      "current_budget": 632.08,
      "forecast": 706.99,
      "suggested": 657.06,
      "final": 657.06,
      "expected_saving": -227.31,
      "expected_saving_pct": -0.5289,
      "confidence_high": 5,
      "confidence_medium": 18,
      "confidence_low": 9,
      "planning_enabled": true,
      "state": "DRAFT",
      "plan_month": "2026-10-01",
      "scenario": "REALISTIC"
    },
    "AGGRESSIVE": {
      "current_budget": 587.07,
      "forecast": 706.99,
      "suggested": 575.58,
      "final": 575.58,
      "expected_saving": -145.83,
      "expected_saving_pct": -0.3393,
      "confidence_high": 5,
      "confidence_medium": 18,
      "confidence_low": 9,
      "planning_enabled": true,
      "state": "DRAFT",
      "plan_month": "2026-10-01",
      "scenario": "AGGRESSIVE"
    }
  },
  "plannerRows": [
    {
      "id_category": "54635eebe66f",
      "domain": "PERSONAL",
      "category": "Alimentación",
      "subcategory": "Comer fuera",
      "forecast_type": "SPARSE",
      "confidence": "MEDIUM",
      "confidence_score": 3,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 16.01,
      "current_mtd": 13.0,
      "previous_same_period": 18.21,
      "projected_close": 15.57,
      "forecast_next_month": 11.3,
      "suggested_budget": 9.61,
      "manual_budget": null,
      "final_budget": 9.61,
      "scenario_factor": 0.8504
    },
    {
      "id_category": "3278ef5ecc17",
      "domain": "PERSONAL",
      "category": "Alimentación",
      "subcategory": "Comida a domicilio",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 7.86,
      "current_mtd": 26.78,
      "previous_same_period": 2.78,
      "projected_close": 23.06,
      "forecast_next_month": 15.29,
      "suggested_budget": 13.0,
      "manual_budget": null,
      "final_budget": 13.0,
      "scenario_factor": 0.8502
    },
    {
      "id_category": "2be100bef176",
      "domain": "PERSONAL",
      "category": "Alimentación",
      "subcategory": "Mercado / Hogar",
      "forecast_type": "VARIABLE",
      "confidence": "HIGH",
      "confidence_score": 5,
      "flexibility": "MEDIUM",
      "is_essential": 1,
      "current_budget": 230.0,
      "current_mtd": 133.38,
      "previous_same_period": 116.5,
      "projected_close": 218.7,
      "forecast_next_month": 229.95,
      "suggested_budget": 220.75,
      "manual_budget": null,
      "final_budget": 220.75,
      "scenario_factor": 0.96
    },
    {
      "id_category": "aa0d86fff83b",
      "domain": "PERSONAL",
      "category": "Alimentación",
      "subcategory": "Snacks / Antojos",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 31.14,
      "current_mtd": 23.16,
      "previous_same_period": 33.82,
      "projected_close": 32.74,
      "forecast_next_month": 40.05,
      "suggested_budget": 34.04,
      "manual_budget": null,
      "final_budget": 34.04,
      "scenario_factor": 0.8499
    },
    {
      "id_category": "d0edce306bff",
      "domain": "PERSONAL",
      "category": "Casa",
      "subcategory": "Productos de Limpieza",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 9.43,
      "previous_same_period": 0.0,
      "projected_close": 9.43,
      "forecast_next_month": 1.63,
      "suggested_budget": 1.3,
      "manual_budget": null,
      "final_budget": 1.3,
      "scenario_factor": 0.7975
    },
    {
      "id_category": "e44b00735c98",
      "domain": "PERSONAL",
      "category": "Comisiones",
      "subcategory": "Bancarias",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "LOW",
      "is_essential": 1,
      "current_budget": 3.13,
      "current_mtd": 4.02,
      "previous_same_period": 4.73,
      "projected_close": 5.07,
      "forecast_next_month": 5.55,
      "suggested_budget": 5.27,
      "manual_budget": null,
      "final_budget": 5.27,
      "scenario_factor": 0.9495
    },
    {
      "id_category": "cdeaa858d23e",
      "domain": "PERSONAL",
      "category": "Comisiones",
      "subcategory": "Pago móvil",
      "forecast_type": "VARIABLE",
      "confidence": "HIGH",
      "confidence_score": 5,
      "flexibility": "LOW",
      "is_essential": 1,
      "current_budget": 0.87,
      "current_mtd": 1.0,
      "previous_same_period": 0.94,
      "projected_close": 1.49,
      "forecast_next_month": 1.57,
      "suggested_budget": 1.49,
      "manual_budget": null,
      "final_budget": 1.49,
      "scenario_factor": 0.949
    },
    {
      "id_category": "628890685d73",
      "domain": "PERSONAL",
      "category": "Cuidado personal",
      "subcategory": "Barbería / Estética",
      "forecast_type": "SPARSE",
      "confidence": "MEDIUM",
      "confidence_score": 3,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 11.0,
      "current_mtd": 0.0,
      "previous_same_period": 5.34,
      "projected_close": 1.92,
      "forecast_next_month": 5.5,
      "suggested_budget": 3.85,
      "manual_budget": null,
      "final_budget": 3.85,
      "scenario_factor": 0.7
    },
    {
      "id_category": "838f43099b97",
      "domain": "PERSONAL",
      "category": "Deuda / CASHEA",
      "subcategory": "Cuota existente",
      "forecast_type": "DEBT",
      "confidence": "HIGH",
      "confidence_score": 5,
      "flexibility": "NONE",
      "is_essential": 1,
      "current_budget": 131.65,
      "current_mtd": 110.97,
      "previous_same_period": 73.03,
      "projected_close": 166.04,
      "forecast_next_month": 166.04,
      "suggested_budget": 166.04,
      "manual_budget": null,
      "final_budget": 166.04,
      "scenario_factor": 1.0
    },
    {
      "id_category": "867f66f96e27",
      "domain": "PERSONAL",
      "category": "Deuda / CASHEA",
      "subcategory": "Nueva compra / Inicial",
      "forecast_type": "DEBT",
      "confidence": "MEDIUM",
      "confidence_score": 3,
      "flexibility": "NONE",
      "is_essential": 1,
      "current_budget": 4.91,
      "current_mtd": 3.3,
      "previous_same_period": 4.91,
      "projected_close": 4.91,
      "forecast_next_month": 4.91,
      "suggested_budget": 4.91,
      "manual_budget": null,
      "final_budget": 4.91,
      "scenario_factor": 1.0
    },
    {
      "id_category": "187086ab6ed2",
      "domain": "PERSONAL",
      "category": "Gastos Anilet",
      "subcategory": "Alimentación",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 12.08,
      "current_mtd": 3.93,
      "previous_same_period": 12.1,
      "projected_close": 6.53,
      "forecast_next_month": 10.15,
      "suggested_budget": 8.12,
      "manual_budget": null,
      "final_budget": 8.12,
      "scenario_factor": 0.8
    },
    {
      "id_category": "90ed95be3e3a",
      "domain": "PERSONAL",
      "category": "Gastos Anilet",
      "subcategory": "Cuidado personal",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 0.0,
      "previous_same_period": 0.0,
      "projected_close": 0.0,
      "forecast_next_month": 2.88,
      "suggested_budget": 2.3,
      "manual_budget": null,
      "final_budget": 2.3,
      "scenario_factor": 0.7986
    },
    {
      "id_category": "bb9aa44c26fa",
      "domain": "PERSONAL",
      "category": "Gastos Anilet",
      "subcategory": "Otros",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.26,
      "current_mtd": 0.0,
      "previous_same_period": 0.26,
      "projected_close": 6.43,
      "forecast_next_month": 14.94,
      "suggested_budget": 11.95,
      "manual_budget": null,
      "final_budget": 11.95,
      "scenario_factor": 0.7999
    },
    {
      "id_category": "09084abc7d9e",
      "domain": "PERSONAL",
      "category": "Gastos Anilet",
      "subcategory": "Salud",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.4,
      "current_mtd": 0.0,
      "previous_same_period": 0.4,
      "projected_close": 0.23,
      "forecast_next_month": 0.47,
      "suggested_budget": 0.38,
      "manual_budget": null,
      "final_budget": 0.38,
      "scenario_factor": 0.8085
    },
    {
      "id_category": "7ffa9252daaa",
      "domain": "PERSONAL",
      "category": "Gastos Anilet",
      "subcategory": "Telecomunicaciones",
      "forecast_type": "SPARSE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 1.26,
      "current_mtd": 2.41,
      "previous_same_period": 0.0,
      "projected_close": 2.41,
      "forecast_next_month": 0.92,
      "suggested_budget": 0.74,
      "manual_budget": null,
      "final_budget": 0.74,
      "scenario_factor": 0.8043
    },
    {
      "id_category": "ac0462b7d93d",
      "domain": "PERSONAL",
      "category": "Mascotas",
      "subcategory": "Veterinario",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 19.6,
      "previous_same_period": 0.0,
      "projected_close": 19.6,
      "forecast_next_month": 0.0,
      "suggested_budget": 0.0,
      "manual_budget": null,
      "final_budget": 0.0,
      "scenario_factor": 0.0
    },
    {
      "id_category": "ea13bd34de82",
      "domain": "PERSONAL",
      "category": "Moto",
      "subcategory": "Reparación",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 50.0,
      "previous_same_period": 0.0,
      "projected_close": 50.0,
      "forecast_next_month": 0.0,
      "suggested_budget": 0.0,
      "manual_budget": null,
      "final_budget": 0.0,
      "scenario_factor": 0.0
    },
    {
      "id_category": "57aa1b426750",
      "domain": "PERSONAL",
      "category": "Movilidad",
      "subcategory": "Envío / Mandado personal",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 0.0,
      "previous_same_period": 0.0,
      "projected_close": 0.0,
      "forecast_next_month": 0.98,
      "suggested_budget": 0.69,
      "manual_budget": null,
      "final_budget": 0.69,
      "scenario_factor": 0.7041
    },
    {
      "id_category": "0c4ed6ac46b7",
      "domain": "PERSONAL",
      "category": "Movilidad",
      "subcategory": "Transporte público",
      "forecast_type": "VARIABLE",
      "confidence": "HIGH",
      "confidence_score": 5,
      "flexibility": "LOW",
      "is_essential": 1,
      "current_budget": 1.34,
      "current_mtd": 2.14,
      "previous_same_period": 1.21,
      "projected_close": 2.12,
      "forecast_next_month": 1.61,
      "suggested_budget": 1.53,
      "manual_budget": null,
      "final_budget": 1.53,
      "scenario_factor": 0.9503
    },
    {
      "id_category": "5d0a9aae4767",
      "domain": "PERSONAL",
      "category": "Movilidad",
      "subcategory": "Traslado personal",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "LOW",
      "is_essential": 1,
      "current_budget": 37.37,
      "current_mtd": 43.23,
      "previous_same_period": 24.21,
      "projected_close": 52.49,
      "forecast_next_month": 42.66,
      "suggested_budget": 40.53,
      "manual_budget": null,
      "final_budget": 40.53,
      "scenario_factor": 0.9501
    },
    {
      "id_category": "6f8244597d9a",
      "domain": "PERSONAL",
      "category": "Ocio",
      "subcategory": "Entretenimiento",
      "forecast_type": "VARIABLE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 2.02,
      "current_mtd": 0.0,
      "previous_same_period": 2.0,
      "projected_close": 3.49,
      "forecast_next_month": 7.84,
      "suggested_budget": 6.27,
      "manual_budget": null,
      "final_budget": 6.27,
      "scenario_factor": 0.7997
    },
    {
      "id_category": "aa17195d22a1",
      "domain": "PERSONAL",
      "category": "Ocio",
      "subcategory": "Hotel / Alojamiento",
      "forecast_type": "SPARSE",
      "confidence": "MEDIUM",
      "confidence_score": 3,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 27.98,
      "current_mtd": 13.84,
      "previous_same_period": 13.78,
      "projected_close": 21.88,
      "forecast_next_month": 13.84,
      "suggested_budget": 11.07,
      "manual_budget": null,
      "final_budget": 11.07,
      "scenario_factor": 0.7999
    },
    {
      "id_category": "04850e7d0477",
      "domain": "PERSONAL",
      "category": "Salud",
      "subcategory": "Medicinas",
      "forecast_type": "SPARSE",
      "confidence": "HIGH",
      "confidence_score": 5,
      "flexibility": "MEDIUM",
      "is_essential": 1,
      "current_budget": 25.0,
      "current_mtd": 0.0,
      "previous_same_period": 0.69,
      "projected_close": 0.12,
      "forecast_next_month": 0.52,
      "suggested_budget": 0.42,
      "manual_budget": null,
      "final_budget": 0.42,
      "scenario_factor": 0.8077
    },
    {
      "id_category": "90cdacd86983",
      "domain": "PERSONAL",
      "category": "Salud",
      "subcategory": "Otros Salud",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 27.2,
      "previous_same_period": 0.0,
      "projected_close": 27.2,
      "forecast_next_month": 0.23,
      "suggested_budget": 0.14,
      "manual_budget": null,
      "final_budget": 0.14,
      "scenario_factor": 0.6087
    },
    {
      "id_category": "37808d2d38fd",
      "domain": "PERSONAL",
      "category": "Suscripciones / Herramientas",
      "subcategory": "CapCut",
      "forecast_type": "FIXED",
      "confidence": "MEDIUM",
      "confidence_score": 3,
      "flexibility": "NONE",
      "is_essential": 1,
      "current_budget": 10.01,
      "current_mtd": 0.0,
      "previous_same_period": 10.01,
      "projected_close": 10.01,
      "forecast_next_month": 10.01,
      "suggested_budget": 10.01,
      "manual_budget": null,
      "final_budget": 10.01,
      "scenario_factor": 1.0
    },
    {
      "id_category": "7824bf9385e0",
      "domain": "PERSONAL",
      "category": "Suscripciones / Herramientas",
      "subcategory": "ChatGPT",
      "forecast_type": "FIXED",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "NONE",
      "is_essential": 1,
      "current_budget": 20.0,
      "current_mtd": 0.0,
      "previous_same_period": 0.0,
      "projected_close": 20.0,
      "forecast_next_month": 20.0,
      "suggested_budget": 20.0,
      "manual_budget": null,
      "final_budget": 20.0,
      "scenario_factor": 1.0
    },
    {
      "id_category": "e1859a227ab4",
      "domain": "PERSONAL",
      "category": "Suscripciones / Herramientas",
      "subcategory": "RIAL",
      "forecast_type": "FIXED",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "NONE",
      "is_essential": 1,
      "current_budget": 5.79,
      "current_mtd": 0.0,
      "previous_same_period": 0.0,
      "projected_close": 5.79,
      "forecast_next_month": 5.79,
      "suggested_budget": 5.79,
      "manual_budget": null,
      "final_budget": 5.79,
      "scenario_factor": 1.0
    },
    {
      "id_category": "1c88ad89731f",
      "domain": "PERSONAL",
      "category": "Tecnología",
      "subcategory": "Equipos",
      "forecast_type": "SPARSE",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 5.0,
      "current_mtd": 0.0,
      "previous_same_period": 4.97,
      "projected_close": 0.87,
      "forecast_next_month": 8.24,
      "suggested_budget": 5.77,
      "manual_budget": null,
      "final_budget": 5.77,
      "scenario_factor": 0.7002
    },
    {
      "id_category": "6ac5147cff31",
      "domain": "PERSONAL",
      "category": "Telecomunicaciones",
      "subcategory": "Internet",
      "forecast_type": "FIXED",
      "confidence": "MEDIUM",
      "confidence_score": 4,
      "flexibility": "NONE",
      "is_essential": 1,
      "current_budget": 32.0,
      "current_mtd": 37.21,
      "previous_same_period": 40.69,
      "projected_close": 40.69,
      "forecast_next_month": 40.69,
      "suggested_budget": 40.69,
      "manual_budget": null,
      "final_budget": 40.69,
      "scenario_factor": 1.0
    },
    {
      "id_category": "665b6fb63cde",
      "domain": "PERSONAL",
      "category": "Trabajo / Trámites",
      "subcategory": "Documentos / Gestiones",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "MEDIUM",
      "is_essential": 0,
      "current_budget": 15.0,
      "current_mtd": 0.0,
      "previous_same_period": 0.0,
      "projected_close": 0.0,
      "forecast_next_month": 20.88,
      "suggested_budget": 14.62,
      "manual_budget": null,
      "final_budget": 14.62,
      "scenario_factor": 0.7002
    },
    {
      "id_category": "3b87de5f1ff5",
      "domain": "PERSONAL",
      "category": "Trabajo / Trámites",
      "subcategory": "Mensajería / Traslado de documentos",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "MEDIUM",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 0.0,
      "previous_same_period": 0.0,
      "projected_close": 0.0,
      "forecast_next_month": 1.15,
      "suggested_budget": 0.8,
      "manual_budget": null,
      "final_budget": 0.8,
      "scenario_factor": 0.6957
    },
    {
      "id_category": "875fba7cfcd9",
      "domain": "PERSONAL",
      "category": "Vestimenta",
      "subcategory": "Ropa",
      "forecast_type": "SPARSE",
      "confidence": "LOW",
      "confidence_score": 2,
      "flexibility": "HIGH",
      "is_essential": 0,
      "current_budget": 0.0,
      "current_mtd": 19.59,
      "previous_same_period": 0.0,
      "projected_close": 22.6,
      "forecast_next_month": 21.4,
      "suggested_budget": 14.98,
      "manual_budget": null,
      "final_budget": 14.98,
      "scenario_factor": 0.7
    }
  ],
  "movements": {
    "total": 474,
    "limit": 50,
    "offset": 0,
    "items": [
      {
        "date": "2026-09-26",
        "description": "Binance Earn",
        "domain": "PERSONAL",
        "category": "Ingresos",
        "subcategory": "Rendimientos",
        "account": "Binance",
        "amount_usd": 0.42,
        "type": "Ingreso"
      },
      {
        "date": "2026-09-26",
        "description": "Meta Ads",
        "domain": "NEGOCIO",
        "category": "PremiadosVE",
        "subcategory": "Meta Ads / Publicidad",
        "account": "Binance",
        "amount_usd": 20.15,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Pago Cashea Yummy",
        "domain": "PERSONAL",
        "category": "Deuda / CASHEA",
        "subcategory": "Cuota existente",
        "account": "BNC",
        "amount_usd": 3.6,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Pago cuota Cashea miniso",
        "domain": "PERSONAL",
        "category": "Deuda / CASHEA",
        "subcategory": "Cuota existente",
        "account": "BNC",
        "amount_usd": 12.76,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Pago Cuota Cashea Traki",
        "domain": "PERSONAL",
        "category": "Deuda / CASHEA",
        "subcategory": "Cuota existente",
        "account": "BNC",
        "amount_usd": 9.9,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Pago Cashea Yummy",
        "domain": "PERSONAL",
        "category": "Deuda / CASHEA",
        "subcategory": "Cuota existente",
        "account": "BNC",
        "amount_usd": 6.79,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Pago cashea Yummy",
        "domain": "PERSONAL",
        "category": "Deuda / CASHEA",
        "subcategory": "Cuota existente",
        "account": "BNC",
        "amount_usd": 4.51,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Pago Cashea bulls burger",
        "domain": "PERSONAL",
        "category": "Deuda / CASHEA",
        "subcategory": "Cuota existente",
        "account": "BNC",
        "amount_usd": 3.0,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Pago Cashea yummy",
        "domain": "PERSONAL",
        "category": "Deuda / CASHEA",
        "subcategory": "Cuota existente",
        "account": "BNC",
        "amount_usd": 3.92,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Entrada en BNC",
        "domain": "PATRIMONIAL",
        "category": "Transferencias",
        "subcategory": "Transferencia interna entrada",
        "account": "BNC",
        "amount_usd": 52.08,
        "type": "Transferencia (entrada)"
      },
      {
        "date": "2026-09-26",
        "description": "Comisión por transferencia",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Bancarias",
        "account": "Binance",
        "amount_usd": 0.06,
        "type": "Egreso"
      },
      {
        "date": "2026-09-26",
        "description": "Salida desde Binance",
        "domain": "PATRIMONIAL",
        "category": "Transferencias",
        "subcategory": "Transferencia interna salida",
        "account": "Binance",
        "amount_usd": 52.08,
        "type": "Transferencia (salida)"
      },
      {
        "date": "2026-09-24",
        "description": "Rechazo zinli comisión",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Bancarias",
        "account": "Zinli",
        "amount_usd": 0.39,
        "type": "Egreso"
      },
      {
        "date": "2026-09-24",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-24",
        "description": "Yummy Casa - Daka",
        "domain": "PERSONAL",
        "category": "Movilidad",
        "subcategory": "Traslado personal",
        "account": "BNC",
        "amount_usd": 4.69,
        "type": "Egreso"
      },
      {
        "date": "2026-09-23",
        "description": "Compra de Jabón en polvo",
        "domain": "PERSONAL",
        "category": "Casa",
        "subcategory": "Productos de Limpieza",
        "account": "BNC",
        "amount_usd": 0.74,
        "type": "Egreso"
      },
      {
        "date": "2026-09-22",
        "description": "Panes campesinos",
        "domain": "PERSONAL",
        "category": "Alimentación",
        "subcategory": "Snacks / Antojos",
        "account": "BNC",
        "amount_usd": 1.29,
        "type": "Egreso"
      },
      {
        "date": "2026-09-22",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-22",
        "description": "Pago adicional veterinario y medicamentos",
        "domain": "PERSONAL",
        "category": "Mascotas",
        "subcategory": "Veterinario",
        "account": "BNC",
        "amount_usd": 2.35,
        "type": "Egreso"
      },
      {
        "date": "2026-09-22",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.05,
        "type": "Egreso"
      },
      {
        "date": "2026-09-22",
        "description": "Consulta veterinaria de Bruno",
        "domain": "PERSONAL",
        "category": "Mascotas",
        "subcategory": "Veterinario",
        "account": "BNC",
        "amount_usd": 17.25,
        "type": "Egreso"
      },
      {
        "date": "2026-09-22",
        "description": "Entrada en BNC",
        "domain": "PATRIMONIAL",
        "category": "Transferencias",
        "subcategory": "Transferencia interna entrada",
        "account": "BNC",
        "amount_usd": 20.06,
        "type": "Transferencia (entrada)"
      },
      {
        "date": "2026-09-22",
        "description": "Comisión por transferencia",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Bancarias",
        "account": "Binance",
        "amount_usd": 0.05,
        "type": "Egreso"
      },
      {
        "date": "2026-09-22",
        "description": "Salida desde Binance",
        "domain": "PATRIMONIAL",
        "category": "Transferencias",
        "subcategory": "Transferencia interna salida",
        "account": "Binance",
        "amount_usd": 20.06,
        "type": "Transferencia (salida)"
      },
      {
        "date": "2026-09-21",
        "description": "Cuenta por coborar Moto - 1era cuota",
        "domain": "PATRIMONIAL",
        "category": "Cuentas por cobrar",
        "subcategory": "Cobro CxC",
        "account": "Efectivo",
        "amount_usd": 10.0,
        "type": "Ingreso"
      },
      {
        "date": "2026-09-21",
        "description": "Cuenta por cobrar Moto - 2da cuota",
        "domain": "PATRIMONIAL",
        "category": "Cuentas por cobrar",
        "subcategory": "Cobro CxC",
        "account": "Binance",
        "amount_usd": 50.0,
        "type": "Ingreso"
      },
      {
        "date": "2026-09-21",
        "description": "Entrada en BNC",
        "domain": "PATRIMONIAL",
        "category": "Transferencias",
        "subcategory": "Transferencia interna entrada",
        "account": "BNC",
        "amount_usd": 42.51,
        "type": "Transferencia (entrada)"
      },
      {
        "date": "2026-09-21",
        "description": "Comisión por transferencia",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Bancarias",
        "account": "Binance",
        "amount_usd": 0.05,
        "type": "Egreso"
      },
      {
        "date": "2026-09-21",
        "description": "Salida desde Binance",
        "domain": "PATRIMONIAL",
        "category": "Transferencias",
        "subcategory": "Transferencia interna salida",
        "account": "Binance",
        "amount_usd": 42.51,
        "type": "Transferencia (salida)"
      },
      {
        "date": "2026-09-21",
        "description": "Pago de plan Movistar",
        "domain": "PERSONAL",
        "category": "Telecomunicaciones",
        "subcategory": "Internet",
        "account": "BNC",
        "amount_usd": 6.47,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Yummy Caobos - Anilet - Casa",
        "domain": "PERSONAL",
        "category": "Movilidad",
        "subcategory": "Traslado personal",
        "account": "BNC",
        "amount_usd": 2.3,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.04,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Perros donde Juan",
        "domain": "PERSONAL",
        "category": "Alimentación",
        "subcategory": "Comida a domicilio",
        "account": "BNC",
        "amount_usd": 14.91,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Hotel Cantaura",
        "domain": "PERSONAL",
        "category": "Ocio",
        "subcategory": "Hotel / Alojamiento",
        "account": "BNC",
        "amount_usd": 13.84,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Yummy  Honda - Centro",
        "domain": "PERSONAL",
        "category": "Movilidad",
        "subcategory": "Traslado personal",
        "account": "BNC",
        "amount_usd": 3.37,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Recarga movistar",
        "domain": "PERSONAL",
        "category": "Telecomunicaciones",
        "subcategory": "Internet",
        "account": "BNC",
        "amount_usd": 0.94,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Pago taxi tocuyito - honda",
        "domain": "PERSONAL",
        "category": "Alimentación",
        "subcategory": "Snacks / Antojos",
        "account": "BNC",
        "amount_usd": 2.35,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comision por error",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Bancarias",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Pago taxi Rescatar a Macarena",
        "domain": "PERSONAL",
        "category": "Movilidad",
        "subcategory": "Traslado personal",
        "account": "BNC",
        "amount_usd": 2.12,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Moto taxi honda",
        "domain": "PERSONAL",
        "category": "Alimentación",
        "subcategory": "Snacks / Antojos",
        "account": "BNC",
        "amount_usd": 0.47,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Pasaje",
        "domain": "PERSONAL",
        "category": "Movilidad",
        "subcategory": "Transporte público",
        "account": "Efectivo",
        "amount_usd": 0.24,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Panes campesinos Honda",
        "domain": "PERSONAL",
        "category": "Alimentación",
        "subcategory": "Snacks / Antojos",
        "account": "BNC",
        "amount_usd": 2.0,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Comisión por pago móvil",
        "domain": "PERSONAL",
        "category": "Comisiones",
        "subcategory": "Pago móvil",
        "account": "BNC",
        "amount_usd": 0.02,
        "type": "Egreso"
      },
      {
        "date": "2026-09-20",
        "description": "Yummy Santa Rosa Ahorcado",
        "domain": "PERSONAL",
        "category": "Movilidad",
        "subcategory": "Traslado personal",
        "account": "BNC",
        "amount_usd": 3.07,
        "type": "Egreso"
      },
      {
        "date": "2026-09-18",
        "description": "Panes campesinos",
        "domain": "PERSONAL",
        "category": "Alimentación",
        "subcategory": "Snacks / Antojos",
        "account": "BNC",
        "amount_usd": 1.53,
        "type": "Egreso"
      }
    ]
  }
};
